# TODO ADD IN VIDEO_FACE_EXTRACTOR AND VIDEO_INDEXING_TEST DOCUMENTATION
PERSON_TRACKING_HSV_CHANNELS_NR = 1
PERSON_TRACKING_USE_MASK = True

PERSON_TRACKING_HSV_CHANNELS_NR_KEY = 'nr_of_hsv_channels_in_person_tracking'
PERSON_TRACKING_USE_MASK_KEY = 'use_mask_in_person_tracking'